---
AllCops:
  TargetRubyVersion: 2.5
Metrics/LineLength:
  Max: 140
Metrics/MethodLength:
  Max: 100
Metrics/BlockLength:
  Max: 70
Metrics/AbcSize:
  Max: 40
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MixinUsage:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
