---
AllCops:
  TargetRubyVersion: 2.5
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 140
Metrics/MethodLength:
  Max: 100
Metrics/BlockLength:
  Max: 50
Metrics/AbcSize:
  Max: 40
Style/StringLiterals:
  EnforcedStyle: double_quotes
